---
- hosts: localhost
  tasks:
  - name: Set Engine public key as authorized key without validating the TLS/SSL certificates
    connection: ssh
    authorized_key:
      user: root
      state: present
      # The certificate has to be verified by the user for its authenticity
      key: https://{{ he_fqdn }}/ovirt-engine/services/pki-resource?resource=engine-certificate&format=OPENSSH-PUBKEY
      validate_certs: False
    delegate_to: "{{ host }}"
    with_items: "{{ groups['gluster'] }}"
    loop_control:
      loop_var: host
    when: "'gluster' in groups"

  - name: Add additional gluster hosts to engine
    async: 50
    poll: 0
    ignore_errors: true
    ovirt_host:
     cluster: "{{ he_cluster }}"
     name: "{{ host }}"
     address: "{{ host }}"
     state: present
     public_key: true
     auth: "{{ ovirt_auth }}"
     hosted_engine: deploy
    with_items: "{{ groups['gluster'] }}"
    loop_control:
     loop_var: host
    when: "'gluster' in groups"

  - name: "Add additional glusterfs storage domains"
    ignore_errors: true
    ovirt_storage_domain:
      name: "{{ sd.name }}"
      domain_function: "{{  sd.function  }}"
      host: "{{ he_host_name }}"
      auth: "{{ ovirt_auth }}"
      data_center: "{{ datacenter_name }}"
      glusterfs:
        address: "{{ he_storage_domain_addr }}"
        mount_options: "{{ sd.mount_options }}"
        path: "{{ sd.path }}"
    with_items: "{{ hostvars[groups['gluster'][0]]['storage_domains'] }}"
    loop_control:
      loop_var: sd
    when: "'gluster' in groups"
