---

# Gluster deployment start here
- name: Setup backend and deploy HCI
  hosts: hc-nodes
  remote_user: root
  gather_facts: no
  any_errors_fatal: true

  roles:
     - gluster.infra
     - gluster.features
